apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  template: 
    metadata:
      name: app_pod
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: gcr.io/k8sdemoproject/mypythonapp:0.1
          ports:
            - containerPort: 5000
          env:
            - name: HOSTNAME
              value: "- Python App Host"
      imagePullSecrets:
        - name: gcr-json-key

  replicas: 1
  selector:
    matchLabels:
      app: app


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: app-ingress
spec:
  rules:
    - host: "*.xip.io"
      http:
        paths:
          - path: /greetings
            backend:
              serviceName: app-service
              servicePort: 5000
          - path: /square
            backend:
              serviceName: app-service
              servicePort: 5000

