---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: add jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0440'

- name: rpm jenkins import
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: upgrade all packages
  yum:
    name: '*'
    state: latest


- name: Install jenkins packages
  yum:
    name:
      - jenkins
      - java-1.8.0-openjdk-devel
    state: present

- name: Start Jenkins service
  service: 
    name: jenkins
    state: started
    enabled: yes  